### ISSUE TITLE
Getting started...

### ISSUE THREAD

**Issue by rossbar** [vanvalenlab/cellSAM#1]
Thanks for uploading @rdilip 

The first order of business is to define an interface for users. IMO the easiest way to start is with a minimal set of examples in the README.

One component that is obviously necessary to make this usable is the model itself. We can start by ensuring that the current version is available on users.deepcell.org. From [perusing the code](https://github.com/vanvalenlab/cellSAM/blob/0a151125ead91935f9a7eb448d0b77edb8f2e7da/model.py#L151) it looks like these assets are necessary in order to perform inference. Are there others?

**Comment by ellenemerson** [comment]
I think some of the model setup w/ loading the .pth and setting threshold parameters that is in that main function could be put into a constructor or something similar.

It would also be helpful to make this pip installable at some point.

**Comment by rossbar** [comment]
There's been a decent amount of progress since this was opened so it's no longer particularly relevant. I'll go ahead and close it and we can focus on specifics moving forward. Thanks @ellenemerson and @rdilip !
